name: Build and Deploy to AWS S3 static hosting

on:
  workflow_dispatch:
    inputs:
      aws-region:
        type: choice
        description: AWS Region
        options:
          - us-east-1
          - us-west-2
      api-url:
        type: string
        description: AWS hosted API url

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        run: npm run build
        env:
          VITE_API_URI: ${{ inputs.api-url }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.aws-region }}

      - name: Sync built files to S3
        run: aws s3 sync ./dist s3://$AWS_S3_BUCKET --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

